import Nav from '@/components/Nav'
import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <div className='  text-text   w-full  flex flex-col items-center min-h-screen bg-background ' >
          <Nav />
          {children}
        </div>

      </body>
    </html>
  )
}
