import './globals.css'
import NavBar from '@/components/NavBar'
import { SessionProvider } from "next-auth/react"



export const metadata = {
  title: 'Eco Swap',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <body >
        <SessionProvider  >

        <div className='  text-text  w-full  flex flex-col items-center min-h-screen justify-center bg-background' >
          <NavBar />
            <div className='w-[85%] flex flex-col h-full items-center justify-center  my-14 '>
              {children}
            </div>
          
        </div>
        </SessionProvider>

      </body>
    </html>
  )
}
